Traceback (most recent call last):
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\Hacer_Backup.py", line 172, in <module>
    observer.start()
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\observers\api.py", line 265, in start
    emitter.start()
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\utils\__init__.py", line 86, in start
    self.on_thread_start()
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\observers\read_directory_changes.py", line 53, in on_thread_start
    self._whandle = get_directory_handle(self.watch.path)
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\observers\winapi.py", line 321, in get_directory_handle
    return CreateFileW(
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\observers\winapi.py", line 115, in _errcheck_handle
    raise ctypes.WinError()
FileNotFoundError: [WinError 3] El sistema no puede encontrar la ruta especificada.
Traceback (most recent call last):
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\Hacer_Backup.py", line 172, in <module>
    observer.start()
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\observers\api.py", line 265, in start
    emitter.start()
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\utils\__init__.py", line 86, in start
    self.on_thread_start()
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\observers\read_directory_changes.py", line 53, in on_thread_start
    self._whandle = get_directory_handle(self.watch.path)
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\observers\winapi.py", line 321, in get_directory_handle
    return CreateFileW(
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\observers\winapi.py", line 115, in _errcheck_handle
    raise ctypes.WinError()
FileNotFoundError: [WinError 3] El sistema no puede encontrar la ruta especificada.
Traceback (most recent call last):
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\Hacer_Backup.py", line 172, in <module>
    observer.start()
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\observers\api.py", line 265, in start
    emitter.start()
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\utils\__init__.py", line 86, in start
    self.on_thread_start()
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\observers\read_directory_changes.py", line 53, in on_thread_start
    self._whandle = get_directory_handle(self.watch.path)
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\observers\winapi.py", line 321, in get_directory_handle
    return CreateFileW(
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\observers\winapi.py", line 115, in _errcheck_handle
    raise ctypes.WinError()
FileNotFoundError: [WinError 3] El sistema no puede encontrar la ruta especificada.
Traceback (most recent call last):
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\Hacer_Backup.py", line 172, in <module>
    observer.start()
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\observers\api.py", line 265, in start
    emitter.start()
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\utils\__init__.py", line 86, in start
    self.on_thread_start()
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\observers\read_directory_changes.py", line 53, in on_thread_start
    self._whandle = get_directory_handle(self.watch.path)
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\observers\winapi.py", line 321, in get_directory_handle
    return CreateFileW(
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\observers\winapi.py", line 115, in _errcheck_handle
    raise ctypes.WinError()
FileNotFoundError: [WinError 3] El sistema no puede encontrar la ruta especificada.
Traceback (most recent call last):
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\Hacer_Backup.py", line 172, in <module>
    observer.start()
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\observers\api.py", line 265, in start
    emitter.start()
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\utils\__init__.py", line 86, in start
    self.on_thread_start()
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\observers\read_directory_changes.py", line 53, in on_thread_start
    self._whandle = get_directory_handle(self.watch.path)
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\observers\winapi.py", line 321, in get_directory_handle
    return CreateFileW(
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\observers\winapi.py", line 115, in _errcheck_handle
    raise ctypes.WinError()
FileNotFoundError: [WinError 3] El sistema no puede encontrar la ruta especificada.
Traceback (most recent call last):
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\Hacer_Backup.py", line 172, in <module>
    observer.start()
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\observers\api.py", line 265, in start
    emitter.start()
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\utils\__init__.py", line 86, in start
    self.on_thread_start()
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\observers\read_directory_changes.py", line 53, in on_thread_start
    self._whandle = get_directory_handle(self.watch.path)
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\observers\winapi.py", line 321, in get_directory_handle
    return CreateFileW(
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\observers\winapi.py", line 115, in _errcheck_handle
    raise ctypes.WinError()
FileNotFoundError: [WinError 3] El sistema no puede encontrar la ruta especificada.
Traceback (most recent call last):
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\Hacer_Backup.py", line 172, in <module>
    observer.start()
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\observers\api.py", line 265, in start
    emitter.start()
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\utils\__init__.py", line 86, in start
    self.on_thread_start()
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\observers\read_directory_changes.py", line 53, in on_thread_start
    self._whandle = get_directory_handle(self.watch.path)
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\observers\winapi.py", line 321, in get_directory_handle
    return CreateFileW(
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\observers\winapi.py", line 115, in _errcheck_handle
    raise ctypes.WinError()
FileNotFoundError: [WinError 3] El sistema no puede encontrar la ruta especificada.
Traceback (most recent call last):
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\Hacer_Backup.py", line 172, in <module>
    observer.start()
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\observers\api.py", line 265, in start
    emitter.start()
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\utils\__init__.py", line 86, in start
    self.on_thread_start()
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\observers\read_directory_changes.py", line 53, in on_thread_start
    self._whandle = get_directory_handle(self.watch.path)
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\observers\winapi.py", line 321, in get_directory_handle
    return CreateFileW(
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\observers\winapi.py", line 115, in _errcheck_handle
    raise ctypes.WinError()
FileNotFoundError: [WinError 3] El sistema no puede encontrar la ruta especificada.
Traceback (most recent call last):
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\Hacer_Backup.py", line 172, in <module>
    observer.start()
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\observers\api.py", line 265, in start
    emitter.start()
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\utils\__init__.py", line 86, in start
    self.on_thread_start()
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\observers\read_directory_changes.py", line 53, in on_thread_start
    self._whandle = get_directory_handle(self.watch.path)
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\observers\winapi.py", line 321, in get_directory_handle
    return CreateFileW(
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\observers\winapi.py", line 115, in _errcheck_handle
    raise ctypes.WinError()
FileNotFoundError: [WinError 3] El sistema no puede encontrar la ruta especificada.
Traceback (most recent call last):
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\Hacer_Backup.py", line 172, in <module>
    observer.start()
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\observers\api.py", line 265, in start
    emitter.start()
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\utils\__init__.py", line 86, in start
    self.on_thread_start()
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\observers\read_directory_changes.py", line 53, in on_thread_start
    self._whandle = get_directory_handle(self.watch.path)
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\observers\winapi.py", line 321, in get_directory_handle
    return CreateFileW(
  File "C:\Users\HAZEL\Desktop\Python\Servicio_Backup_SEISSP\myvenv\lib\site-packages\watchdog\observers\winapi.py", line 115, in _errcheck_handle
    raise ctypes.WinError()
FileNotFoundError: [WinError 3] El sistema no puede encontrar la ruta especificada.
